"""empty message

Revision ID: 7a28feef4832
Revises:
Create Date: 2023-03-22 13:32:19.790508

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '7a28feef4832'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=40), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=40), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('profile_picture', sa.String(
                        length=255), nullable=True),
                    sa.Column('gender', sa.String(length=10), nullable=False),
                    sa.Column('birthday', sa.Date(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('activities',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=40), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(length=20), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.Column('distance', sa.Float(
                        precision=1, asdecimal=True), nullable=False),
                    sa.Column('duration', sa.Integer(), nullable=False),
                    sa.Column('calories', sa.Integer(), nullable=True),
                    sa.Column('elevation', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    if environment == "production":
        op.execute(f"ALTER TABLE activities SET SCHEMA {SCHEMA};")

    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.String(length=255), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('activity_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['activity_id'], ['activities.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('activities')
    op.drop_table('users')
    # ### end Alembic commands ###
